version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flask python-dotenv
  e2e:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flask python-dotenv
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Clone frontend and run e2e
          command: |
            cd ../
            git clone git@github.com:ashleemboyer/react-flask-testing-frontend.git
            cd react-flask-testing-frontend
            yarn test:e2e
workflows:
  version: 2
  all:
    jobs:
      - build
      - e2e
